Homework 12 done
eugene-okulik/sokolip pull request #11
Opened 2024-07-16 15:07 UTC by sokolip

2024-07-17 08:06 UTC, eugene-okulik requested changes
Всё отлично, но только класс ничего не знает о том какие там объекты будут созданы из этого класса. Он должен работать с данными текущего объекта, который создан на основе этого класса. Ведь объект buket_1 могут и не создать, а создать объект my_buket.

2024-07-17 08:06 UTC, eugene-okulik commented on homework/ivan_sokolskii/Homework_12/task_1.py
> +                print(flower)
Есть еще вот такое короткое решение того же:
```python
def sort_flowers_by(self, key='color'):
    self.flowers.sort(key=lambda x: getattr(x, key))
```

2024-07-17 08:06 UTC, eugene-okulik commented on homework/ivan_sokolskii/Homework_12/task_1.py
> +                print(flower)
Если я сделаю еще один объект букета
```python
buket_2 = Buket()
buket_2.add_flowers(red_rose)
buket_2.add_flowers(big_daisy)
buket_2.add_flowers(pink_tulp)
```
А потом сделаю для него 
```python
buket_2.sort_flowers_by('color')
```
То я получу список цветов из первого букета, ведь в классе написано, что нужно распечатывать не цветы из текущего объекта букета, а именно из объекта, который называется `buket_1`

2024-07-17 18:05 UTC, sokolip commented
Когда я изменил метод сортировки, как ты указал, то получил такую ошибку:
elf.flowers.sort(key=lambda x: getattr(x, key))
TypeError: '<' not supported between instances of 'int' and 'str'
пришлось все же делать через фильтры, правильно ли я понял?

2024-07-18 08:25 UTC, eugene-okulik commented
> Когда я изменил метод сортировки, как ты указал, то получил такую ошибку: elf.flowers.sort(key=lambda x: getattr(x, key)) TypeError: '<' not supported between instances of 'int' and 'str' пришлось все же делать через фильтры, правильно ли я понял?

Это значит, что в каком-то из свойств у тебя хранится что-то не то. Возможно из-за этой строки
```python
big_daisy = Daisy('b_daisy' 'white', 3, 6, 80, 15, 'no', True)
```
Здесь ты при создании цветка передаешь 8 параметров, хотя класс ждет только 7. Скорее всего, какой-то из параметров лег в каое-то не то свойство.

2024-07-18 08:30 UTC, eugene-okulik approved these changes

2024-07-18 08:30 UTC, eugene-okulik commented on homework/ivan_sokolskii/Homework_12/task_1.py
> +red_rose = Rose('r_rose', 'red', 1, 11, 120, 17, 'no')
В параметры prickle и bush ты передаешь 'yes' или 'no'. В программировании для такого существует тип данных `boolean`.

2024-07-18 08:31 UTC, merged

2024-07-18 12:52 UTC, sokolip commented on homework/ivan_sokolskii/Homework_12/task_1.py
> +red_rose = Rose('r_rose', 'red', 1, 11, 120, 17, 'no')
Да, я изначально туда передавал True и False, но у меня возникала ошибка