Homework_15 done
eugene-okulik/sokolip pull request #14
Opened 2024-07-24 16:30 UTC by sokolip

2024-07-24 16:42 UTC, sokolip commented
Привет, не пойму на что он ругается, ошибка о лишних пробелах, после последнего символа в строке, но у меня там нет пробелов.

2024-07-24 16:59 UTC, eugene-okulik requested changes
В этом задании ты так же как и в прошлом выполнил задание не в той последовательности. Прошлое я принял с оговоркой, что в этом задании нужно будет соблюсти ту последовательность, которая в задании.

2024-07-24 16:59 UTC, eugene-okulik commented on homework/ivan_sokolskii/Homework_15/task_1.py
> +INSERT INTO `groups` (title, start_date, end_date)
В этой строке у тебя в конце есть пробел после закрывающей скобки. ВОт на него и ругается

2024-07-24 16:59 UTC, eugene-okulik commented on homework/ivan_sokolskii/Homework_15/task_1.py
> +trith_less_wor_id_query = cursor.execute("SELECT id from lessons ORDER BY id DESC LIMIT 1 OFFSET 1")
Если в момент между тем как ты добавил запись и запросил вот так последнюю кто-то вставит еще одну запись, то айди у тебя будет не тот.  
Да, после executemany невозможно получить вставленные айди, подтому нужно добавлять записи по одной и сохранять их айди.

2024-07-24 17:11 UTC, sokolip commented on homework/ivan_sokolskii/Homework_15/task_1.py
> +INSERT INTO `groups` (title, start_date, end_date)
мне показалось, что литер ругается на 51 строку,  а не на 11, спасибо

2024-07-24 17:12 UTC, eugene-okulik commented on homework/ivan_sokolskii/Homework_15/task_1.py
> +INSERT INTO `groups` (title, start_date, end_date)
> мне показалось, что литер ругается на 51 строку, а не на 11, спасибо

На 51-й символ в этой строке он ругался

2024-07-25 07:22 UTC, eugene-okulik approved these changes
В запросах можно использовать обычную питоновскую подстановку, но если будет=шь выполнять что-то подобное в качестве тестового задания, лучше использовать подстановку защищенную от инъекций.

2024-07-25 07:22 UTC, merged