Homework 23 done
eugene-okulik/sokolip pull request #22
Opened 2024-09-13 13:46 UTC by sokolip

2024-09-14 09:31 UTC, eugene-okulik requested changes
Всё хорошо, кроме одного места. Нужно помнить, что автотесты - это тоже программа. А любую программу всегда нужно протестить и убедиться, что она правильно выполняет всё, что должна.

2024-09-14 09:31 UTC, eugene-okulik commented on homework/ivan_sokolskii/Homework_23/task_2.py
> +subject_field.send_keys(subjects)
Посмотри внимательно - после того как ты заполнил это поле и пошел к следующим шагам, это поле остается незаполненным. Нужно руками разобраться как правильно работать с этим полем и потом заавтоматизировать эти действия.

2024-09-15 22:46 UTC, sokolip commented
Понял, исправил

2024-09-16 09:18 UTC, eugene-okulik approved these changes

2024-09-16 09:19 UTC, merged