Ivan: Homework 4 completed
eugene-okulik/sokolip pull request #3
Opened 2024-06-24 20:03 UTC by sokolip

2024-06-25 09:43 UTC, eugene-okulik requested changes
Всё отлично, но одну проверочку на внимательность не прошел )))

2024-06-25 09:43 UTC, eugene-okulik commented on homework/ivan_sokolskii/Homework_4/Homework.py
> +my_dict['dict']['i am a tuple'] = 'good'
В задании было:

> добавьте элемент с ключом ('i am a tuple',) и любым значением

У тебя выполнено как если бы там было

> добавьте элемент с ключом 'i am a tuple' и любым значением

`('i am a tuple',) ` - кортеж с одним элементом. И именно это и должно быть ключом. Сейчас ключ - строка `'i am a tuple'`

2024-06-25 19:44 UTC, sokolip commented
Да, пропустил этот момент

2024-06-26 08:24 UTC, eugene-okulik approved these changes

2024-06-26 08:25 UTC, merged