Ivan: homework 5 completed
eugene-okulik/sokolip pull request #4
Opened 2024-06-26 16:00 UTC by sokolip

Не уверен, что все сделал оптимальным путем, но работает)

2024-06-26 16:33 UTC, sokolip commented
Добавил новую версию принта, когда пересмотрел лекцию в текстовом формате

2024-06-27 06:09 UTC, eugene-okulik requested changes

2024-06-27 06:09 UTC, eugene-okulik commented on homework/ivan_sokolskii/Homework_5/Homework.py
> +num_3 += 10
В примерах - варианты того, как может ответить программа. Нам нужно сделать один код, который сможет работать с любым из вариантов ответа. То есть обработать каждую переменную абсолютно одинаковым кодом. Пока что делаем это копируя код, потом будем учиться как избежать здесь этого копирования.  
Для этого нужно найти в этих строках что-то одинаковое: количество символов перед числом разное; количество символов в числе тоже разное. Но есть в структуре всех строк что-то одинаковое и на это можно опереться.

2024-06-27 13:02 UTC, sokolip commented
Тогда так будет более правильно

2024-06-28 09:21 UTC, eugene-okulik requested changes

2024-06-28 09:21 UTC, eugene-okulik commented on homework/ivan_sokolskii/Homework_5/Homework.py
> +result_number_3 = int(result_3.split(":")[-1].strip())
Было бы шикарным решением, если бы в задании не было указано

> С помощью срезов и метода index получите из каждой строки с результатом число

Твое решение более оптимально, если в задании нет дополнительных условий, но они есть. Кстати, еще более оптимально было бы не заморачиваться на двоеточие, а делить просто по пробелам (дефолтовое поведение функции split)

2024-06-28 15:17 UTC, sokolip commented on homework/ivan_sokolskii/Homework_5/Homework.py
> +result_number_3 = int(result_3.split(":")[-1].strip())
Исправил, методы извлечения числа из строки

2024-06-29 07:47 UTC, eugene-okulik approved these changes
:+1:

2024-06-29 07:47 UTC, merged