Homework_8 done
eugene-okulik/sokolip pull request #7
Opened 2024-07-07 17:28 UTC by sokolip

Не распечатывается 100000 число, говорит не хватает памяти, или что-то такое

2024-07-07 19:02 UTC, eugene-okulik commented
> Не распечатывается 100000 число, говорит не хватает памяти, или что-то такое

Это типа поднастроить можно, если хочется, но можно изабить. )) Если интересно, можешь загуглить.

2024-07-07 19:03 UTC, eugene-okulik requested changes
Всё хорошо, но нужно избавиться от ошибок линта.

2024-07-08 02:40 UTC, sokolip commented
готово

2024-07-08 08:09 UTC, eugene-okulik approved these changes

2024-07-08 08:10 UTC, merged